/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#0c6780',
        'on-primary': '#ffffff',
        'primary-container': '#87ceeb',
        'on-primary-container': '#005870',
        'inverse-primary': '#89d0ed',
        'primary-fixed': '#baeaff',
        'primary-fixed-dim': '#89d0ed',
        'on-primary-fixed': '#001f29',
        'on-primary-fixed-variant': '#004d62',
        'secondary': '#705d00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fcd400',
        'on-secondary-container': '#6e5c00',
        'secondary-fixed': '#ffe16d',
        'secondary-fixed-dim': '#e9c400',
        'on-secondary-fixed': '#221b00',
        'on-secondary-fixed-variant': '#544600',
        'tertiary': '#70585b',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#dbbdc0',
        'on-tertiary-container': '#624b4e',
        'tertiary-fixed': '#fbdbde',
        'tertiary-fixed-dim': '#debfc2',
        'on-tertiary-fixed': '#281719',
        'on-tertiary-fixed-variant': '#574144',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface': '#fbf9f8',
        'surface-dim': '#dbd9d9',
        'surface-bright': '#fbf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f3',
        'surface-container': '#efeded',
        'surface-container-high': '#eae8e7',
        'surface-container-highest': '#e4e2e2',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#3f484c',
        'surface-variant': '#e4e2e2',
        'surface-tint': '#0c6780',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f2f0f0',
        'outline': '#6f787d',
        'outline-variant': '#bfc8cd',
        'background': '#fbf9f8',
        'on-background': '#1b1c1c',
        'sky-blue-light': '#E0F4FF',
        'gold-soft': '#FFF4BD',
        'safety-green': '#A8E6CF',
        'critical-coral': '#FF8B94',
      },
      borderRadius: {
        'sm': '0.5rem',
        'DEFAULT': '1rem',
        'md': '1.5rem',
        'lg': '2rem',
        'xl': '3rem',
        'full': '9999px',
      },
      spacing: {
        'unit': '8px',
        'gutter': '24px',
        'margin-mobile': '24px',
        'margin-desktop': '64px',
        'touch-target-min': '56px',
      },
      fontFamily: {
        'headline-lg': ['Quicksand', 'sans-serif'],
        'headline-lg-mobile': ['Quicksand', 'sans-serif'],
        'headline-md': ['Quicksand', 'sans-serif'],
        'button-text': ['Quicksand', 'sans-serif'],
        'body-lg': ['Nunito Sans', 'sans-serif'],
        'body-md': ['Nunito Sans', 'sans-serif'],
        'label-lg': ['Nunito Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg-mobile': ['26px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '30px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '700', letterSpacing: '0.5px' }],
        'button-text': ['18px', { lineHeight: '24px', fontWeight: '600' }],
      },
      boxShadow: {
        'soft': '0 10px 40px -10px rgba(12, 103, 128, 0.1)',
        'neomorphic': '10px 10px 20px rgba(0,0,0,0.02), -10px -10px 20px rgba(255,255,255,0.8)',
      },
      keyframes: {
        floating: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'pulse-soft': {
          '0%, 100%': { transform: 'scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.05)', opacity: '0.8' },
        },
        'pulse-red': {
          '0%': { transform: 'scale(1)', boxShadow: '0 0 0 0 rgba(255, 139, 148, 0.7)' },
          '70%': { transform: 'scale(1.02)', boxShadow: '0 0 0 15px rgba(255, 139, 148, 0)' },
          '100%': { transform: 'scale(1)', boxShadow: '0 0 0 0 rgba(255, 139, 148, 0)' },
        },
        blob: {
          '0%': { transform: 'scale(1)' },
          '100%': { transform: 'scale(1.2)' },
        },
      },
      animation: {
        floating: 'floating 4s ease-in-out infinite',
        'pulse-soft': 'pulse-soft 3s infinite ease-in-out',
        'pulse-red': 'pulse-red 2s infinite',
        blob: 'blob 10s infinite alternate',
      },
    },
  },
  plugins: [],
}


